### ISSUE TITLE
Documentation for "Import Culverts" processing algorithm

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-docs#248]
See these tickets for more info and test data: 

https://github.com/nens/threedi-schematisation-editor/issues/127

Download dev version of the 3Di Schematisation Editor here: https://nelenschuurmans-my.sharepoint.com/:f:/g/personal/leendert_vanwolfswinkel_nelen-schuurmans_nl/EhQ_1dDi64JNuafFG6L5gV8BSpifF_75E9UeiQ6O_AdCDw?e=MfsTJM&xsdata=MDV8MDF8fDQwYjMyMzRjNDA1MzRhMjVhY2VhMDhkYjVhOWZjOTMzfDhmNGJmNzQ2ZGUyNDQ1YjA5OTA1NjMzN2FmNDAyNjk3fDB8MHw2MzgyMDM0MTQ1MjQ5NjQwNzR8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPbVJqTkdZNE5qYzVOR1U1T1RSbE9XRmlZalZtTkRka1lUQmpNV1F5TWpZd1FIUm9jbVZoWkM1Mk1pOXRaWE56WVdkbGN5OHhOamcwTnpRME5qVXhPVGcxfGIwOWRiZWI0OGZjYTQ4ZWFhY2VhMDhkYjVhOWZjOTMzfGU3Mzg5ODYyMTY1ZTQ0NDBhYTRjNjBlNGEwMzU2YzU4&sdata=WDU5cVV2b20vVHI2dFBGamlzM1ArSndYcXJlMHBYTUM1V3dOemxDVWhiTT0%3D&ovuser=8f4bf746-de24-45b0-9905-6337af402697%2CLeendert.vanWolfswinkel%40nelen-schuurmans.nl

**Comment by JohannaLems** [comment]
Ik snapte neit zoe goed wat ik hier precies moest doen. Er is ook alweer een nieuwere versie van de 3Di Schematisation Editor beschikbaar volgensmij.
