### ISSUE TITLE
a_howto_calculation_point_distance

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-docs#285]
- should have an illustration to show how calculation point distance works.
- "40 x 40 m^2" should use math expression
- Needs a link to concepts where is explained what double connectec, connected, embedded etc is (`h_1d2d_exchange.rst`)
- "Pipes can also be given a connected calculation type, in combination with a calculation point distance that is smaller than the length of the pipe. In this way, the pipe can exchange with 2D cells it crosses. This can be used as a way to schematise gullies." This also needs an illustraion

**Comment by JohannaLems** [comment]
the illustration to show how calculation point distance works, already exists: https://docs.3di.live/h_computational_grid.html#calculation-point-distance
