### ISSUE TITLE
h_control.html

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-docs#294]
- Make header level of 'Table control' and 'Memory control' one header level lower
- 'Timed control' is missing
- Use "m MSL" instead of "mNAP" 
- Rewrite for readability
- Check with the API documentation to make sure that all Control structure functionalities are covered

**Comment by Jonasvsl** [comment]
needs an example json file

**Comment by Jonasvsl** [comment]
"state_detail": {
                "Invalid": "Either 'timed', 'table' or 'memory' needs to be present in json file, see documentation"
            }

**Comment by Jonasvsl** [comment]
example

{
    "timed": [
        {
            "offset": 1800,
            "duration": 1800,
            "value": [
                0.0, 0.0
            ],
            "type": "set_discharge_coefficients",
            "structure_id": 65,
            "structure_type": "v2_weir"
        }
    ],

    "timed": [
        {
            "offset": 0,
            "duration": 1800,
            "value": [
                0.0, 0.0
            ],
            "type": "set_discharge_coefficients",
            "structure_id": 100004,
            "structure_type": "v2_weir"
        }
    ]	
}

**Comment by leendertvanwolfswinkel** [comment]
Documentatie waar hier naar verwezen wordt is de docs bij het POST endpoint, zie swagger

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by leendertvanwolfswinkel** [comment]
@NoortjeOosterhoff1996 @kasperlange ik heb jullie even beiden geassigned, kunnen jullie onderling afstemmen wie hier als eerste aan toe komt?

**Comment by Jonasvsl** [comment]
dit zou echt heel relaxed zijn om te hebben voor het mkdc project. ze hebben 70 controlled structures en ze willen graag weten hoe die te implementeren. kunnen jullie een seintje geven als het er in zit?

**Comment by NoortjeOosterhoff1996** [comment]
Ik ben aankomende twee weken op vakantie, daarna heb ik tijd om aan de documentatie van Control Structures te werken. Hoe zit jij @kasperlange?

**Comment by kasperlange** [comment]
Ik had heel veel gedoe om alles aan de praat krijgen, omdat ik opeens niks meer kan installeren op mijn laptop en Wim is blijkbaar de enige die dat zou kunnen fixen, maar die is met vakantie. Daarom heb ik uiteindelijk maar een een leenlaptop gekregen waar ik alle software op heb geinstalleerd (Github & Docker).

Ik denk niet dat ik het deze week nog red. @NoortjeOosterhoff1996 Laten we volgende week even afstemmen als je weer terug bent.
