### ISSUE TITLE
Maximum water depth processing algorithm documentation

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-docs#348]

**Comment by leendertvanwolfswinkel** [comment]
In 3Di Toolbox 2.5.4, a new processing algorithm has been added.

Please add documentation to this section: https://docs.3di.live/i_analyzing_results.html#calculate-waterdepth-and-waterlevel-maps

Please also correct the existing documentation on the water depth and water level (_these are two separate words in English, with a space between water and depth / water and level_) algorithms, because I immediately spotted some strange things.

BTW when we replace the 3Di Toolbox by 3Di Results Analysis, this part will remain exactly the same

**Comment by kasperlange** [comment]
New location: https://docs.staging.3di.live/i_processing_toolbox.html
